### ISSUE TITLE
Add LICENSE files

### ISSUE THREAD

**Issue by Daniel-Mietchen** [bigscience/bigscience.github.io#1]
to clarify reusability of the code in
- this repo
- https://github.com/bigscience/institutionsmaps
- https://github.com/bigscience/bigscience

Perhaps use the MIT License, as per
- https://github.com/bigscience/sciencemaps

**Comment by filipinascimento** [comment]
Thanks for noticing that! It was supposed to have the LICENSE here as well.  Fixed in  532e53e
